Repository symfony/demo, pull requests merged in 2018-05, with the labels that each got.

#793 Remove default flex id
  composer.json
Labels: FINISHED

#798 Minor french translation mistake on comment_error
  translations/messages.fr.xlf
Labels: FINISHED, bug

#800 Updated the app to Symfony 4.1 beta1
  composer.json
  composer.lock
  templates/blog/post_show.html.twig
Labels: FINISHED, Feature

#801 Add Bulgarian language
  config/services.yaml
  translations/messages.bg.xlf
  translations/validators.bg.xlf
Labels: FINISHED, Feature

#803 Updated to Symfony 4.1 beta2
  composer.lock
Labels: FINISHED, Feature

#805 Moved Doctrine Fixtures bundle to dev and test only
  composer.json
  composer.lock
  config/bundles.php
  symfony.lock
Labels: FINISHED, Feature

#806 Updated to Symfony 4.1 beta3
  composer.lock
Labels: FINISHED, Feature
