Repository symfony/demo, pull requests merged in 2018-09, with the labels that each got.

#846 Updating `.lock` files for security reasons
  .travis.yml
  composer.lock
  symfony.lock
Labels: FINISHED, bug

#847 Add Turkish language
  config/services.yaml
  translations/messages.tr.xlf
  translations/validators.tr.xlf
Labels: FINISHED, Feature

#845 Update dutch language file.
  translations/messages.nl.xlf
Labels: FINISHED, bug

#857 Updating Yarn dependencies, making build process work again
  package.json
  public/build/css/admin.0856c04f.css
  public/build/css/app.644c8031.css
  public/build/css/app.css
  public/build/fonts/fontawesome-webfont.674f50d2.eot
  public/build/fonts/fontawesome-webfont.af7ae505.woff2
  public/build/fonts/fontawesome-webfont.b06871f2.ttf
  public/build/fonts/fontawesome-webfont.fee66e71.woff
  public/build/fonts/glyphicons-halflings-regular.eot
  public/build/fonts/glyphicons-halflings-regular.ttf
  public/build/fonts/glyphicons-halflings-regular.woff
  public/build/fonts/glyphicons-halflings-regular.woff2
  public/build/fonts/lato-bold-italic.0b6bb672.woff2
  public/build/fonts/lato-bold-italic.9c7e4e9e.woff
  public/build/fonts/lato-bold.cccb8974.woff2
  public/build/fonts/lato-bold.d878b6c2.woff
  public/build/fonts/lato-normal-italic.4eb103b4.woff2
  public/build/fonts/lato-normal-italic.f28f2d64.woff
  public/build/fonts/lato-normal.27bd77b9.woff
  public/build/fonts/lato-normal.bd03a2cc.woff2
  public/build/images/fontawesome-webfont.912ec66d.svg
  public/build/images/glyphicons-halflings-regular.svg
  public/build/js/admin.24f0f27f.js
  public/build/js/admin.js
  public/build/js/app.3d70fef3.js
  public/build/js/app.js
  public/build/js/common.4a5a2dfe.js
  public/build/js/common.js
  public/build/js/login.7d4dcfc1.js
  public/build/js/login.js
  public/build/js/search.d3a1f656.js
  public/build/js/search.js
  public/build/manifest.d41d8cd9.js
  public/build/manifest.js
  public/build/manifest.json
  webpack.config.js
  yarn.lock
Labels: FINISHED

#861 Fix /var configuration in .gitignore
  .gitignore
Labels: FINISHED, bug
