Repository symfony/demo, pull requests merged in 2018-06, with the labels that each got.

#814 require phpunit 7.1 via SYMFONY_PHPUNIT_VERSION env variable
  .travis.yml
  phpunit.xml.dist
Labels: FINISHED, bug

#816 Add help messages to some form fields
  src/Form/CommentType.php
  src/Form/PostType.php
  templates/blog/_comment_form.html.twig
Labels: Feature

#823 Use PHP_OS_FAMILY constant thanks to Symfony's PHP 7.2 polyfill
  composer.json
  composer.lock
  tests/Command/AddUserCommandTest.php
Labels: FINISHED
