Repository symfony/demo, pull requests merged in 2019-06, with the labels that each got.

#979 Remove beta minimum stability
  composer.json
Labels: FINISHED, bug

#984 Fail CI if the repo is in a dirty state after building assets
  .travis.yml
Labels: FINISHED, Feature

#982 Rebuild assets and return back styles
  public/build/2.88407626.js
  public/build/app.b82aa2d9.css
  public/build/entrypoints.json
  public/build/manifest.json
Labels: FINISHED, bug

#1000 use phpunit 7.5
  bin/phpunit
  phpunit.xml.dist
Labels: FINISHED, bug

#1001 revert fixtures db change
  data/database.sqlite
  data/database_test.sqlite
Labels: FINISHED, bug

#1003 Apply latest changes in FWBundle recipe
  config/bootstrap.php
Labels: FINISHED

#1002 chore(phpunit): remove lines for `SYMFONY_PHPUNIT_REMOVE`
  bin/phpunit
Labels: FINISHED
