Repository symfony/demo, pull requests merged in 2019-07, with the labels that each got.

#1008 Be more specific in linting twig and yaml files
  .travis.yml
Labels: FINISHED, Feature

#1007 Add symfony 4.4 and 5.0 to .travis.yml
  .travis.yml
Labels: FINISHED

#1014 Use HTTPS and fix a url
  .env
Labels: FINISHED

#1015 Fix pagination class
  templates/blog/index.html.twig
Labels: FINISHED, bug

#1006 Added a Paginator object based on Doctrine's paginator
  src/Pagination/Paginator.php
  src/Repository/PostRepository.php
  templates/blog/index.html.twig
Labels: FINISHED, Feature

#1016 Lithuanian translations for validator
  translations/validators+intl-icu.lt.xlf
Labels: FINISHED, Feature
