Repository symfony/demo, pull requests merged in 2020-01, with the labels that each got.

#1058 Use new functional test specific assertions
  tests/Controller/Admin/BlogControllerTest.php
  tests/Controller/BlogControllerTest.php
  tests/Controller/DefaultControllerTest.php
  tests/Controller/UserControllerTest.php
Labels: FINISHED

#1064 Use short syntax for routes HTTP methods
  src/Controller/Admin/BlogController.php
  src/Controller/BlogController.php
  src/Controller/UserController.php
Labels: FINISHED

#1063 Replaced SwiftMailer by Symfony Mailer
  .env
  composer.json
  composer.lock
  config/bundles.php
  config/packages/dev/mailer.yaml
  config/packages/dev/swiftmailer.yaml
  config/packages/mailer.yaml
  config/packages/swiftmailer.yaml
  config/packages/test/mailer.yaml
  config/packages/test/swiftmailer.yaml
  src/Command/ListUsersCommand.php
  src/EventSubscriber/CommentNotificationSubscriber.php
  symfony.lock
  tests/Command/AddUserCommandTest.php
Labels: Feature

#1067 Validate composer files while TravisCI build
  .travis.yml
Labels: FINISHED, Feature

#1066 Remove "symfony/polyfill-php72" from the dependencies
  composer.json
  composer.lock
  symfony.lock
Labels: FINISHED

#1070 Require symfony/apache-pack package
  composer.json
  composer.lock
  public/.htaccess
  symfony.lock
Labels: FINISHED, Feature

#1074 Use a more friendly message about hardcoding user details
  assets/js/login.js
Labels: FINISHED

#1073 Add a translation for a message about slug uniqueness
  src/Entity/Post.php
  translations/validators+intl-icu.en.xlf
Labels: FINISHED
